#[derive(Debug, Clone, strum::Display, strum::EnumString, strum::EnumIter)]
pub enum BibleBooks {
    Genesis,
    Exodus,
    Leviticus,
    Numbers,
    Deuteronomy,
    Joshua,
    Judges,
    Ruth,
    #[strum(to_string = "1 Samuel")]
    Samuel1,
    #[strum(to_string = "2 Samuel")]
    Samuel2,
    #[strum(to_string = "1 Kings")]
    Kings1,
    #[strum(to_string = "2 Kings")]
    Kings2,
    #[strum(to_string = "1 Chronicles")]
    Chronicles1,
    #[strum(to_string = "2 Chronicles")]
    Chronicles2,
    Ezra,
    Nehemiah,
    Esther,
    Job,
    Psalms,
    Proverbs,
    Ecclesiastes,
    #[strum(to_string = "Song of Solomon")]
    SongOfSolomon,
    Isaiah,
    Jeremiah,
    Lamentations,
    Ezekiel,
    Daniel,
    Hosea,
    Joel,
    Amos,
    Obadiah,
    Jonah,
    Micah,
    Nahum,
    Habakkuk,
    Zephaniah,
    Haggai,
    Zechariah,
    Malachi,
    Matthew,
    Mark,
    Luke,
    John,
    Acts,
    Romans,
    #[strum(to_string = "1 Corinthians")]
    Corinthians1,
    #[strum(to_string = "2 Corinthians")]
    Corinthians2,
    Galatians,
    Ephesians,
    Philippians,
    Colossians,
    #[strum(to_string = "1 Thessalonians")]
    Thessalonians1,
    #[strum(to_string = "2 Thessalonians")]
    Thessalonians2,
    #[strum(to_string = "1 Timothy")]
    Timothy1,
    #[strum(to_string = "2 Timothy")]
    Timothy2,
    Titus,
    Philemon,
    Hebrews,
    James,
    #[strum(to_string = "1 Peter")]
    Peter1,
    #[strum(to_string = "2 Peter")]
    Peter2,
    #[strum(to_string = "1 John")]
    John1,
    #[strum(to_string = "2 John")]
    John2,
    #[strum(to_string = "3 John")]
    John3,
    Jude,
    Revelation,
}

impl BibleBooks {
    pub fn get_3c_id(&self) -> &'static str {
        match self {
            BibleBooks::Genesis => "GEN",
            BibleBooks::Exodus => "EXO",
            BibleBooks::Leviticus => "LEV",
            BibleBooks::Numbers => "NUM",
            BibleBooks::Deuteronomy => "DEU",
            BibleBooks::Joshua => "JOS",
            BibleBooks::Judges => "JDG",
            BibleBooks::Ruth => "RUT",
            BibleBooks::Samuel1 => "1SA",
            BibleBooks::Samuel2 => "2SA",
            BibleBooks::Kings1 => "1KI",
            BibleBooks::Kings2 => "2KI",
            BibleBooks::Chronicles1 => "1CH",
            BibleBooks::Chronicles2 => "2CH",
            BibleBooks::Ezra => "EZR",
            BibleBooks::Nehemiah => "NEH",
            BibleBooks::Esther => "EST",
            BibleBooks::Job => "JOB",
            BibleBooks::Psalms => "PSA",
            BibleBooks::Proverbs => "PRO",
            BibleBooks::Ecclesiastes => "ECC",
            BibleBooks::SongOfSolomon => "SNG",
            BibleBooks::Isaiah => "ISA",
            BibleBooks::Jeremiah => "JER",
            BibleBooks::Lamentations => "LAM",
            BibleBooks::Ezekiel => "EZK",
            BibleBooks::Daniel => "DAN",
            BibleBooks::Hosea => "HOS",
            BibleBooks::Joel => "JOL",
            BibleBooks::Amos => "AMO",
            BibleBooks::Obadiah => "OBA",
            BibleBooks::Jonah => "JON",
            BibleBooks::Micah => "MIC",
            BibleBooks::Nahum => "NAM",
            BibleBooks::Habakkuk => "HAB",
            BibleBooks::Zephaniah => "ZEP",
            BibleBooks::Haggai => "HAG",
            BibleBooks::Zechariah => "ZEC",
            BibleBooks::Malachi => "MAL",
            BibleBooks::Matthew => "MAT",
            BibleBooks::Mark => "MRK",
            BibleBooks::Luke => "LUK",
            BibleBooks::John => "JHN",
            BibleBooks::Acts => "ACT",
            BibleBooks::Romans => "ROM",
            BibleBooks::Corinthians1 => "1CO",
            BibleBooks::Corinthians2 => "2CO",
            BibleBooks::Galatians => "GAL",
            BibleBooks::Ephesians => "EPH",
            BibleBooks::Philippians => "PHP",
            BibleBooks::Colossians => "COL",
            BibleBooks::Thessalonians1 => "1TH",
            BibleBooks::Thessalonians2 => "2TH",
            BibleBooks::Timothy1 => "1TI",
            BibleBooks::Timothy2 => "2TI",
            BibleBooks::Titus => "TIT",
            BibleBooks::Philemon => "PHM",
            BibleBooks::Hebrews => "HEB",
            BibleBooks::James => "JAS",
            BibleBooks::Peter1 => "1PE",
            BibleBooks::Peter2 => "2PE",
            BibleBooks::John1 => "1JN",
            BibleBooks::John2 => "2JN",
            BibleBooks::John3 => "3JN",
            BibleBooks::Jude => "JUD",
            BibleBooks::Revelation => "REV",
        }
    }

    pub fn chapter_count(&self) -> i64 {
        match self {
            BibleBooks::Genesis => 50,
            BibleBooks::Exodus => 40,
            BibleBooks::Leviticus => 27,
            BibleBooks::Numbers => 36,
            BibleBooks::Deuteronomy => 34,
            BibleBooks::Joshua => 24,
            BibleBooks::Judges => 21,
            BibleBooks::Ruth => 4,
            BibleBooks::Samuel1 => 31,
            BibleBooks::Samuel2 => 24,
            BibleBooks::Kings1 => 22,
            BibleBooks::Kings2 => 25,
            BibleBooks::Chronicles1 => 29,
            BibleBooks::Chronicles2 => 36,
            BibleBooks::Ezra => 10,
            BibleBooks::Nehemiah => 13,
            BibleBooks::Esther => 10,
            BibleBooks::Job => 42,
            BibleBooks::Psalms => 150,
            BibleBooks::Proverbs => 31,
            BibleBooks::Ecclesiastes => 12,
            BibleBooks::SongOfSolomon => 8,
            BibleBooks::Isaiah => 66,
            BibleBooks::Jeremiah => 52,
            BibleBooks::Lamentations => 5,
            BibleBooks::Ezekiel => 48,
            BibleBooks::Daniel => 12,
            BibleBooks::Hosea => 14,
            BibleBooks::Joel => 3,
            BibleBooks::Amos => 9,
            BibleBooks::Obadiah => 1,
            BibleBooks::Jonah => 4,
            BibleBooks::Micah => 7,
            BibleBooks::Nahum => 3,
            BibleBooks::Habakkuk => 3,
            BibleBooks::Zephaniah => 3,
            BibleBooks::Haggai => 2,
            BibleBooks::Zechariah => 14,
            BibleBooks::Malachi => 4,
            BibleBooks::Matthew => 28,
            BibleBooks::Mark => 16,
            BibleBooks::Luke => 24,
            BibleBooks::John => 21,
            BibleBooks::Acts => 28,
            BibleBooks::Romans => 16,
            BibleBooks::Corinthians1 => 16,
            BibleBooks::Corinthians2 => 13,
            BibleBooks::Galatians => 6,
            BibleBooks::Ephesians => 6,
            BibleBooks::Philippians => 4,
            BibleBooks::Colossians => 4,
            BibleBooks::Thessalonians1 => 5,
            BibleBooks::Thessalonians2 => 3,
            BibleBooks::Timothy1 => 6,
            BibleBooks::Timothy2 => 4,
            BibleBooks::Titus => 3,
            BibleBooks::Philemon => 1,
            BibleBooks::Hebrews => 13,
            BibleBooks::James => 5,
            BibleBooks::Peter1 => 5,
            BibleBooks::Peter2 => 3,
            BibleBooks::John1 => 5,
            BibleBooks::John2 => 1,
            BibleBooks::John3 => 1,
            BibleBooks::Jude => 1,
            BibleBooks::Revelation => 22,
        }
    }
}

#[derive(Debug, Clone, strum::Display, strum::EnumString, strum::EnumIter)]
pub enum Translations {
    AAB,
    ARBNAV,
    BSB,
    ENGWEBP,
    GHT,
    GHTG,
    HBOMAS,
    HINIRV,
    aai_wbt,
    aak_wbt,
    aau_wbt,
    aaz_ubb,
    abc_wbt,
    abt_map,
    abt_wos,
    abx_wbt,
    aby_wbt,
    acf_wbt,
    acr_ibs,
    acr_tnt,
    acr_wbt,
    acu_tbl,
    adt_bsa,
    adz_png,
    aer_wbt,
    aey_wbt,
    agd_wbt,
    agg_png,
    agm_png,
    agn_wps,
    agr_wbt,
    agt_wbt,
    agu_nvs,
    ahr_twf,
    aia_wbt,
    aii_abt,
    ake_bss,
    alp_wbt,
    alq_cbs,
    alw_wtw,
    aly_wbt,
    ame_tbl,
    amf_sim,
    amh_amh,
    amk_wbt,
    amm_tbl,
    amn_ana,
    amn_nai,
    amo_d43,
    amp_wbt,
    amr_wbt,
    amu_wbt,
    amx_wbt,
    anh_pbt,
    anv_wbt,
    aoi_bib,
    aoj_fil,
    aoj_wbt,
    aom_tbl,
    aon_wbt,
    apb_wbt,
    ape_bwb,
    ape_cce,
    apn_wbt,
    app_pbt,
    apr_wbt,
    apu_wbt,
    apw_wbt,
    apz_png,
    arb_vdv,
    are_bsa,
    arl_wbt,
    arn_sbu,
    arp_abs,
    asj_wbt,
    asm_irv,
    aso_tbl,
    ata_png,
    atb_wbt,
    atd_wbt,
    atg_wbt,
    att_wbt,
    auc_wbt,
    aui_wbt,
    auy_tbl,
    avt_wbt,
    awb_tbl,
    awk_bsa,
    awx_wbt,
    azb_bsa,
    azg_tbl,
    azz_tbl,
    bao_ntw,
    bba_sim,
    bbb_tbl,
    bbr_wbt,
    bch_png,
    bco_wbt,
    bdd_png,
    bdv_twf,
    bea_bfb,
    bef_wbt,
    bel_jfc,
    bel_njo,
    ben_irv,
    ben_ocv,
    beo_pio,
    beu_ubb,
    bfz_tlf,
    bgc_tlf,
    bgg_twf,
    bgs_wbt,
    bgt_wbt,
    bhd_tlf,
    bhg_wbt,
    bhi_twf,
    bhl_png,
    bht_tlf,
    bhu_twf,
    big_tbl,
    big_wbt,
    bjk_wbt,
    bjp_wbt,
    bjr_wbt,
    bjv_wbt,
    bjz_wbt,
    bkd_wbt,
    bki_wbt,
    bkq_wbt,
    bkw_wbt,
    bkx_ubb,
    bla_cms,
    blw_wbt,
    blz_lai,
    bmh_wbt,
    bmk_wbt,
    bmr_wbt,
    bmu_png,
    bnp_wbt,
    boa_tbl,
    bod_ntb,
    boj_png,
    boj_wbt,
    bon_png,
    box_wyi,
    bpr_wbt,
    bps_wbt,
    bpx_wft,
    bqc_sim,
    bqp_sim,
    bre_brg,
    bsj_doo,
    bsn_tbl,
    bsp_pbt,
    bss_wbt,
    bsw_etw,
    bsw_ltw,
    buk_lbt,
    bus_sim,
    bvd_wbt,
    bvr_wbt,
    bwo_twf,
    bxh_wbt,
    byr_png,
    byr_wag,
    byx_png,
    bzd_wbt,
    bzh_png,
    bzj_wbt,
    caa_wbt,
    cab_png,
    cac_wbt,
    caf_wbt,
    cak_eas,
    cak_sbg,
    cak_sds,
    cak_smj,
    cak_sou,
    cak_swy,
    cak_wes,
    cao_wbt,
    cap_sbb,
    cav_wbt,
    cax_sbb,
    cbc_wbt,
    cbi_wbt,
    cbk_wbt,
    cbr_wbt,
    cbs_wbt,
    cbt_wbt,
    cbu_wbt,
    cbv_wbt,
    cco_tbl,
    cdz_bcs,
    ceb_ocb,
    ceb_ulb,
    cek_akb,
    ces_bib,
    ces_bkr,
    ces_nkb,
    cgc_wbt,
    cha_pga,
    chd_wbt,
    chf_tbl,
    chk_bsm,
    chq_wbt,
    chz_wbt,
    cjo_wbt,
    cjv_tbl,
    ckb_bib,
    cle_tbl,
    clu_wbt,
    cme_ntw,
    cmn_cbs,
    cmn_cbt,
    cmn_cu1,
    cmn_cuv,
    cmn_feb,
    cni_wbt,
    cnl_tbl,
    cnq_wbt,
    cnt_tbl,
    cof_wbt,
    con_wbt,
    cop_bhc,
    cop_cnt,
    cop_shc,
    cot_ntw,
    cpa_tbl,
    cpb_wbt,
    cpc_wbt,
    cpu_wbt,
    cpy_wbt,
    crn_wbt,
    crx_wbt,
    cso_tbl,
    csy_skb,
    cta_wbt,
    cth_bcf,
    ctp_wbt,
    ctu_976,
    ctu_cti,
    ctu_wbt,
    cub_wbt,
    cuc_tbl,
    cui_wbt,
    cuk_nvs,
    cuk_wb9,
    cut_wbt,
    cux_wbt,
    cwe_pbt,
    cya_wbt,
    daa_wyi,
    dad_wbt,
    dah_png,
    dan_det,
    dao_twf,
    ded_wbt,
    deu_elbbk,
    deu_elo,
    deu_l12,
    deu_sch,
    deu_tkw,
    dgc_wbt,
    dgr_cbs,
    dgz_wbt,
    dhg_dol,
    dhg_duw,
    dhn_twf,
    dif_lut,
    dik_wbt,
    dji_wbt,
    djj_wbt,
    djk_wbt,
    djr_bib,
    dne_twf,
    dnv_twf,
    dob_png,
    dop_sim,
    dov_d43,
    dso_twf,
    dwr_ent,
    dwr_ltw,
    dwr_tbl,
    dwu_liv,
    dwu_wbt,
    dww_tbl,
    dwy_bsa,
    ebk_wbt,
    ekk_bib,
    ekk_pkp,
    eko_wbt,
    emi_wbt,
    emp_wyi,
    ena_pbt,
    eng_abt,
    eng_aoi,
    eng_asv,
    eng_bar,
    eng_bbe,
    eng_boy,
    eng_bre,
    eng_cpb,
    eng_dby,
    eng_dra,
    eng_emtv,
    eng_f35,
    eng_fbv,
    eng_glw,
    eng_gnv,
    eng_jps,
    eng_kja,
    eng_kjv,
    eng_lee,
    eng_lsv,
    eng_lxu,
    eng_lxx,
    eng_msb,
    eng_net,
    eng_nna,
    eng_noy,
    eng_ojb,
    eng_oke,
    eng_our,
    eng_pev,
    eng_rv5,
    eng_t4t,
    eng_tce,
    eng_tnt,
    eng_ulb,
    eng_w88,
    eng_wbs,
    eng_web,
    eng_webc,
    eng_webpb,
    eng_webu,
    eng_weu,
    eng_wmb,
    eng_wmu,
    eng_wyc2017,
    eng_wyc2018,
    eng_ylt,
    enq_pn2,
    epo_bfb,
    eri_wbt,
    ese_wbt,
    esk_wbt,
    etr_tbl,
    ewe_bib,
    faa_wbt,
    fad_wbt,
    fai_png,
    far_wbt,
    ffm_wbt,
    fin_bib,
    for_nyb,
    fra_jnd,
    fra_lsg,
    fra_ncl,
    fra_ost,
    fue_sim,
    fuf_pbt,
    fuh_sim,
    gah_png,
    gai_pbt,
    gam_wbt,
    gaq_twf,
    gaw_wbt,
    gax_twf,
    gaz_bib,
    gaz_ebi,
    gbl_bey,
    gdf_tsc,
    gdn_png,
    gdr_png,
    geb_pbt,
    gel_wbt,
    gfk_hwb,
    gfk_swb,
    gfk_tbl,
    gge_wbt,
    ghn_ibm,
    ghs_wbt,
    gia_bsa,
    glk_glk,
    glw_llu,
    gmv_etw,
    gmv_ggm,
    gmv_ltw,
    gmv_wbt,
    gng_wyi,
    gnn_bsa,
    gnw_wbt,
    gof_etw,
    gof_ltw,
    gof_tbl,
    gof_wftw,
    goj_twf,
    gok_twf,
    grc_bre,
    grc_byz,
    grc_f35,
    grc_gtr,
    grc_mtk,
    grc_sbl,
    grc_srg,
    grc_tcg,
    grc_tis,
    gub_wbt,
    gue_wbt,
    guf_wbt,
    guh_wbt,
    gui_sbu,
    guj_irv,
    gul_wbt,
    gum_tbl,
    gun_wbt,
    guo_wbt,
    gup_bsa,
    gup_kwb,
    gup_may,
    gux_ulb,
    gvc_wbt,
    gvf_wbt,
    gvn_wbt,
    gvs_wbt,
    gwi_wbt,
    gyl_twf,
    gym_wbt,
    gyr_wbt,
    gyz_sco,
    hat_bsa,
    hat_pds,
    hau_bib,
    hau_ulb,
    hav_tsc,
    haw_868,
    hbo_wlc,
    hch_wb2,
    hch_wbt,
    heb_lbm,
    heb_mod,
    heb_scg,
    heb_wlc,
    heg_wbt,
    hil_bib,
    hin_cvb,
    hix_wbt,
    hla_png,
    hlb_twf,
    hlt_mcs,
    hlt_thb,
    hmo_png,
    hne_twf,
    hns_wbt,
    hop_wbt,
    hot_wbt,
    hoy_twf,
    hre_bth,
    hru_bcs,
    hrv_bib,
    hrv_iva,
    hrw_wbt,
    hto_wbt,
    hub_wbt,
    hui_png,
    hun_bib,
    hus_tbl,
    hus_wbt,
    huu_wbt,
    huv_tbl,
    hvn_ubb,
    hwo_tsc,
    ian_wbt,
    ibd_wbt,
    ibo_bib,
    idc_sco,
    ign_sbb,
    ikk_wbt,
    ikw_wbt,
    ikz_wbt,
    ilo_ulb,
    imo_tbl,
    inb_wbt,
    ind_ags,
    ind_ayt,
    ind_obo,
    ino_tbl,
    ino_wbt,
    iou_tbl,
    ipi_png,
    isl_bib,
    isn_ulb,
    ita_dio,
    ita_riv,
    iws_tbl,
    ixl_wbt,
    iyx_wbt,
    jac_wbt,
    jae_png,
    jao_wbt,
    jay_wbt,
    jic_wbt,
    jid_nbt,
    jiv_aie,
    jni_ulb,
    jnj_etw,
    jnj_ltw,
    jpn_loc,
    jum_pbt,
    juy_twf,
    jvn_wbt,
    kan_irv,
    kan_okcv,
    kan_swf,
    kaq_wbt,
    kbc_wbt,
    kbh_wbt,
    kbm_tbl,
    kbq_wbt,
    kca_ibt,
    kdc_014,
    kdc_pbt,
    kde_wbt,
    kdl_ldt,
    kdl_wbt,
    kek_ibs,
    ken_wbt,
    kew_png,
    kfc_pwf,
    kff_twf,
    kfw_twf,
    kgf_gbt,
    kgk_wbt,
    kgp_wbt,
    khj_lis,
    khs_wbt,
    khz_png,
    kij_png,
    kik_bib,
    kiw_wbt,
    kiz_ulb,
    kje_wbt,
    kjn_wbt,
    kjs_wbt,
    kkc_wbt,
    kkl_wbt,
    kky_laa,
    klg_wbt,
    klt_wbt,
    klv_wbt,
    kmg_png,
    kmh_kal,
    kmh_min,
    kmk_wbt,
    kmo_bil,
    kms_png,
    kmu_tbl,
    knf_wbt,
    knj_wbt,
    knv_ara,
    knv_png,
    kor_old,
    kos_pub,
    kpf_png,
    kpg_kpt,
    kpj_wbt,
    kpr_tbl,
    kpw_png,
    kpx_tbl,
    kqa_pbt,
    kqc_wbt,
    kqf_wbt,
    kql_pbt,
    kqw_win,
    krh_itd,
    ksd_png,
    ksj_wbt,
    ksr_png,
    ktm_wbt,
    kto_png,
    kud_png,
    kud_wbt,
    kue_png,
    kup_tbl,
    kux_wbt,
    kvg_wbt,
    kvn_wbt,
    kwd_wbt,
    kwf_wbt,
    kwi_wbt,
    kwj_wbt,
    kxv_wft,
    kxw_wbt,
    kyc_png,
    kyf_wbt,
    kyg_tbl,
    kyq_wbt,
    kyz_wbt,
    kze_wbt,
    lac_tbl,
    lag_wbt,
    lat_clv,
    lbb_wbt,
    lbk_wbt,
    lbm_twf,
    lcm_png,
    ldb_wbt,
    leu_png,
    lex_wbt,
    lga_sco,
    lgl_wbt,
    lid_wbt,
    lif_dev,
    lif_wbt,
    lin_bib,
    lit_bbi,
    lit_tpv,
    llg_ubb,
    lng_wbt,
    lth_wbt,
    lug_bib,
    luo_bib,
    lww_wbt,
    lyn_twf,
    maa_sjv,
    maj_btt,
    mal_bib,
    mal_fbf,
    mal_irv,
    mam_com,
    mam_sbg,
    maq_tbl,
    mar_cbi,
    mar_irv,
    mau_wbt,
    mav_wbt,
    maz_tbl,
    mbb_wbt,
    mbc_wbt,
    mbh_tbl,
    mbj_wbt,
    mbl_wbt,
    mbs_wbt,
    mbt_wbt,
    mbu_tsc,
    mca_wbt,
    mcb_wbt,
    mcd_wbt,
    mcf_wbt,
    mco_tbl,
    mcp_wbt,
    mcq_spp,
    mcr_wbt,
    mdy_bse,
    mdy_twf,
    med_png,
    mee_tbl,
    mek_png,
    meq_wbt,
    met_wbt,
    meu_png,
    mey_pbt,
    mfm_sco,
    mfo_lis,
    mfx_ewf,
    mfx_ltw,
    mgc_pbt,
    mgh_wbt,
    mgh_wft,
    mgj_lis,
    mgv_twf,
    mgw_pbt,
    mhl_png,
    mib_wbt,
    mic_cbs,
    mie_tbl,
    mig_wbt,
    mih_wbt,
    mil_tbl,
    mio_wbt,
    mir_tbl,
    mit_ntw,
    miz_tbl,
    mjc_wbt,
    mkj_mok,
    mkl_sim,
    mkn_ubb,
    mks_tbl,
    mkw_wbt,
    mle_wbt,
    mlh_png,
    mlp_tbl,
    mmo_wbt,
    mmx_tbl,
    mna_png,
    mni_twf,
    mop_wbt,
    mox_fns,
    mpa_twf,
    mph_wbt,
    mpj_bsa,
    mpm_tbl,
    mpp_wbt,
    mps_tbl,
    mpt_tbl,
    mpx_png,
    mqb_wbt,
    mqj_wbt,
    msb_wbt,
    msc_pbt,
    msk_wbt,
    msm_wps,
    msy_pbt,
    msy_png,
    mti_tbl,
    mto_wbt,
    mux_tbl,
    muy_wbt,
    mva_png,
    mvn_jlb,
    mwc_wbt,
    mwe_pbt,
    mwf_2018,
    mwp_wbt,
    mxb_mvr,
    mxm_wbt,
    mxp_wbt,
    mxq_tbl,
    mxt_tbl,
    mya_jvb,
    mya_ojv,
    myk_wbt,
    myu_wbt,
    myw_png,
    myy_wbt,
    mzq_sco,
    mzz_wbt,
    nab_wbt,
    naf_tbl,
    nag_ano,
    nak_tbl,
    nal_wbt,
    nas_png,
    nay_afa,
    nbq_wbt,
    nca_wbt,
    nce_wbt,
    ncf_wbt,
    nch_tbl,
    ncj_tbl,
    nck_wbt,
    ncl_tbl,
    ncr_wbt,
    ncu_wbt,
    nde_bib,
    ndg_ulb,
    ndj_twf,
    nfa_ubb,
    ngp_twf,
    ngu_tbl,
    nhe_tbl,
    nhe_wbt,
    nhg_wbt,
    nhi_wbt,
    nho_tct,
    nhu_wbt,
    nhw_tbl,
    nhy_tbl,
    nif_wbt,
    nii_tbl,
    nin_wbt,
    nit_wtf,
    njd_twf,
    nkn_twf,
    nkontw,
    nld,
    nld_1939,
    nld_gbv,
    nld_nbg,
    nlg_wbt,
    nmw_swb,
    nna_wbt,
    nnq_twf,
    noa_wbe,
    noa_wbt,
    nob_lbb,
    nop_ntt,
    not_wbt,
    nou_tbl,
    npi_ncb,
    npi_ulb,
    npl_wyi,
    nrz_nar,
    nsn_wbt,
    nss_wbt,
    ntj_bsa,
    ntp_tbl,
    ntu_wbt,
    nuq_wbt,
    nuy_bsa,
    nvm_wbt,
    nwi_wbt,
    nww_twf,
    nya_bib,
    nys_bsa,
    obo_wbt,
    okv_hwb,
    okv_tbl,
    omb_pbt,
    omw_aat,
    omw_sta,
    omw_veq,
    ong_tbl,
    ons_png,
    ood_wbt,
    opm_tbl,
    ory_irv,
    ote_tbl,
    otm_wbt,
    otn_wbt,
    otq_tbl,
    ots_wbt,
    oyd_etw,
    oyd_ltw,
    pab_tbl,
    pad_wbt,
    pah_tbl,
    pan_irv,
    pao_nab,
    pdo_sco,
    peg_twf,
    pes_opcb,
    pes_pbs,
    pga_pbt,
    pib_wbt,
    pio_wbt,
    pir_wbt,
    piu_bsa,
    pjt_bsa,
    pll_twf,
    pls_wbt,
    plu_wbt,
    pma_wbt,
    poe_tbl,
    poh_bsg,
    poi_wbt,
    pol_bib,
    pol_ubg,
    pon_pja,
    pon_psa,
    pon_ssp,
    pon_sspon,
    por_blj,
    por_blt,
    por_bsl,
    por_onbv,
    por_tft,
    poy_pbt,
    ppo_wbt,
    prf_wbt,
    pri_wbt,
    ptp_tbl,
    ptu_lai,
    pub_twf,
    puu_sco,
    pwg_gtt,
    pwr_twf,
    qub_wbt,
    quc_new,
    quc_tra,
    quc_ttp,
    quf_llb,
    quh_sbb,
    qul_sbb,
    qup_wbt,
    qvc_tbl,
    qve_tbl,
    qvh_wbt,
    qvm_tbl,
    qvn_llb,
    qvs_tbl,
    qvw_wbt,
    qvz_wbt,
    qwh_llb,
    qxh_wbt,
    qxn_wbt,
    qxo_wbt,
    rai_tbl,
    reg_ulb,
    rei_twf,
    rgu_ubb,
    rhg_ctw,
    rhg_sco,
    rif_ati,
    rif_lti,
    rif_tti,
    rkb_wbt,
    rki_twf,
    rmb_wbt,
    rmc_the,
    rmc_zrb,
    rmn_atw,
    rmn_pbt,
    rmy_arl,
    rmy_che,
    rmy_gur,
    rmy_lov,
    rmy_ser,
    rmy_vla,
    ron_924,
    ron_bayash,
    ron_btf,
    ron_lsb,
    ron_lud,
    roo_tbl,
    rop_wbt,
    row_ubb,
    rro_png,
    ruf_pbt,
    rug_wbt,
    rup_twf,
    rus_syn,
    rwo_kar,
    rwo_raw,
    sab_wbt,
    san_asm,
    san_ben,
    san_bur,
    san_col,
    san_dev,
    san_guj,
    san_hks,
    san_ias,
    san_iso,
    san_itr,
    san_kan,
    san_khm,
    san_mal,
    san_ori,
    san_pun,
    san_sin,
    san_tam,
    san_tel,
    san_tha,
    san_tib,
    san_urd,
    san_vel,
    sav_wbt,
    sbe_wbt,
    sbk_ulb,
    sbs_doo,
    sby_twf,
    sce_rsp,
    sch_twf,
    seh_wbt,
    sey_wbt,
    sgb_wbt,
    sgz_wbt,
    shj_pbt,
    shp_tbl,
    shr_buk,
    sim_png,
    six_pbt,
    sja_wbt,
    sle_wft,
    slk_bib,
    sll_tbl,
    smk_wbt,
    sna_bib,
    snc_png,
    snn_wbt,
    snp_kom,
    snp_lam,
    snx_wbt,
    sny_tbl,
    som_sim,
    soq_wbt,
    soy_sim,
    spa_bes,
    spa_blm,
    spa_onbv,
    spa_pdt,
    spa_r09,
    spa_rvg,
    spa_v2p,
    spa_vbl,
    spl_png,
    spm_pbt,
    spp_wbt,
    sps_tbl,
    spy_wbt,
    sri_wbt,
    srm_wbt,
    srn_bss,
    srp_865,
    srp_onspc,
    srp_onstl,
    srq_wbt,
    ssd_wbt,
    ssg_wbt,
    ssx_png,
    stp_tbl,
    stw_wbt,
    sua_tbl,
    sue_wbt,
    sur_itd,
    sus_apb,
    sus_pbt,
    suz_wbt,
    swe_fol,
    swe_svk,
    swh_bib,
    swh_onmm,
    swh_swa,
    swh_ulb,
    swp_png,
    sxb_wbt,
    tac_wbt,
    taj_wbt,
    tam_irv,
    tam_tcv,
    tap_twf,
    tav_wbt,
    taw_pbt,
    tbc_png,
    tbf_man,
    tbg_nor,
    tbg_wbt,
    tbl_wbt,
    tbo_wbt,
    tbx_wbt,
    tbz_sim,
    tca_tbl,
    tcn_twf,
    tcs_wbt,
    tdt_beh,
    tdx_sle,
    tee_tbl,
    tel_irv,
    tel_otsa,
    ter_tbl,
    tet_ubb,
    tew_wbt,
    tfr_wbt,
    tgj_twf,
    tgk_ibt,
    tgl_ulb,
    tgo_wbt,
    tgp_wbt,
    tha_kjv,
    thd_ahh,
    thr_twf,
    tif_wbt,
    tim_tbl,
    tiw_mwb,
    tiw_wbt,
    tiy_wbt,
    tke_wbt,
    tkr_ibt,
    tku_wbt,
    tlf_tbl,
    tmd_wbt,
    tna_wbt,
    tnc_wbt,
    tnk_wbt,
    tnn_wbt,
    tnp_wbt,
    toc_tbl,
    tod_pbt,
    tof_wbt,
    toj_wbt,
    ton_png,
    too_wbt,
    top_wbt,
    tos_tbl,
    tpa_wbt,
    tpi_png,
    tpi_pngon,
    tpt_wbt,
    tpz_wbt,
    trc_tbl,
    tsn_bib,
    tsw_sco,
    tsw_wbt,
    ttc_wbt,
    tte_owb,
    tte_tbl,
    tuc_oov,
    tuc_tua,
    tue_wbt,
    tuf_wbt,
    tuo_wbt,
    tur_obt,
    tur_ytc,
    tvk_wbt,
    tvn_twf,
    tvt_wft,
    twi_aka,
    twi_asa,
    txq_ubb,
    txu_tbl,
    tyx_wbt,
    tzj_eas,
    tzj_wes,
    tzo_hui,
    tzo_san,
    tzo_tzc,
    tzo_tze,
    tzo_zin,
    ubr_tbl,
    ubu_and,
    ubu_kal,
    ubu_nop,
    udu_sim,
    uig_ara,
    uig_cyr,
    uig_lat,
    uig_pin,
    ukr_1996,
    ukr_npu,
    ukr_pan,
    ukr_ufb,
    uli_bsm,
    ulk_wbt,
    unx_twf,
    upv_wbt,
    ura_tbl,
    urb_wbt,
    urd_gvh,
    urd_gvr,
    urd_gvu,
    urd_irv,
    urd_oucv,
    uri_wbt,
    uro_wbt,
    urt_wbt,
    urw_pbt,
    usa_wbt,
    usp_wbt,
    utr_sco,
    uvh_wbt,
    uvl_wbt,
    vaa_wft,
    vgr_wft,
    vid_pbt,
    vie_1934,
    vie_vcb,
    viv_wbt,
    vmy_wbt,
    waj_wbt,
    wal_sim,
    wap_wbt,
    wat_wbt,
    wbi_ulb,
    wbp_wbt,
    wbq_bcs,
    wed_top,
    wed_wbt,
    wer_tbl,
    wim_wbt,
    wiu_tbl,
    wiv_wbt,
    wja_sco,
    wlg_wbt,
    wlo_wbt,
    wmt_wbt,
    wmw_wbt,
    wnc_png,
    wnu_png,
    wol_inj,
    wol_mbs,
    wos_wbt,
    wrk_wbt,
    wro_bfb,
    wrs_png,
    wsk_png,
    wuv_wbt,
    xav_tbl,
    xbi_wam,
    xbi_yan,
    xed_wbt,
    xla_png,
    xnj_twf,
    xnn_wbt,
    xon_wbt,
    xsi_wbt,
    xsn_liz,
    xtd_tbl,
    xtm_wbt,
    yaa_tbl,
    yad_tbl,
    yaf_tsc,
    yal_pbt,
    yao_twf,
    yap_bsm,
    yaq_tbl,
    yby_wbt,
    ycn_wbt,
    ydd_afi,
    yer_lis,
    yij_wbt,
    yka_wbt,
    yle_tbl,
    yml_tbl,
    ymp_sil,
    yns_tsc,
    yom_bib,
    yon_png,
    yor_bib,
    yrb_tbl,
    yre_wbt,
    yss_yam,
    yss_yaw,
    yuj_tbl,
    yut_wbt,
    yuw_png,
    yva_tbl,
    zaa_tbl,
    zab_tbl,
    zac_sim,
    zad_wbt,
    zai_tbl,
    zaj_pbt,
    zaj_ppb,
    zak_wbt,
    zam_ilm,
    zao_tbl,
    zar_tbl,
    zas_wyi,
    zat_wbt,
    zav_tbl,
    zaw_mvr,
    zbu_tsc,
    zca_wyi,
    zga_mul,
    zia_tbl,
    zin_wbt,
    ziw_twf,
    zlm_ksz,
    zlu_tsc,
    zos_tbl,
    zpc_wbt,
    zpi_wyi,
    zpl_tbl,
    zpm_tbl,
    zpo_tbl,
    zpq_tbl,
    zpu_tbl,
    zpv_tbl,
    zpz_tbl,
    zsr_wbt,
    ztp_wbt,
}
